#Numpy


	NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays.
	In NumPy, dimensions are called as axes.


	Why do we need NumPy? [when python lists are already there]

	we cannot perform operations on all the elements of two list directly.
	For example, we cannot multiply two lists directly we will have to do it element wise. 
	This is where the role of NumPy comes into play.




In [ ]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]


print(list1*list2)

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3, 4, 5, 6] 
list2 = [10, 9, 8, 7, 6, 5] 
  
# Convert list1 into a NumPy array 
a1 = np.array(list1) 
  
# Convert list2 into a NumPy array 
a2 = np.array(list2) 
  
print(a1*a2)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype, a.ndim, a.shape)

a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(a, a.dtype, a.ndim, a.shape)

a = np.zeros((3,3))
print(a)

a = np.empty((4,4))
print(a)

b = np.ones_like(a)
print(b)

In [ ]:
x = np.arange(6)
x
x = x.reshape((2, 3))
x
print(np.ones_like(x))


In [ ]:
print(np.linspace(0, 10, 6))
print(np.arange(0, 10, 2))


a = np.arange(6)  
print(a, "np.arange")

b = np.arange(12).reshape(4,3) 
print("np.arange(12).reshape(4,3)")
print(b)

c = np.arange(24).reshape(2,3,4)
print("np.arange(24).reshape(2,3,4)")
print(c)


b = np.arange(12).reshape(3,4)
print("np.arange(12).reshape(3,4)")
print(b)


# Indexing using index arrays

In [ ]:
b

In [ ]:
print(b.sum(axis=0))                     # sum of each column

print(b.min(axis=1))                           # min of each row

In [ ]:
a = np.arange(10)**3
print(a)
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a[2])
# 8
print(a[2:5])
# array([ 8, 27, 64])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)
# array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])
print(a[ : :-1])                                 # reversed a
# array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [ ]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]])

print("Vertical stacking:", np.vstack((a, b))) 
  
# horizontal stacking 
print("Horizontal stacking:", np.hstack((a, b))) 
  
c = [5, 6] 
  
# stacking columns 
print("Column stacking:", np.column_stack((a, c)))



a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 

# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
  
# vertical splitting 
print("Splitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


In [ ]:
a = np.arange(20, 10, -1)  
print("sequential array with a negative step: ",a) 
  
# Indexes are specified inside the np.array method. 
newnp = a[np.array([4, 3, 1, 2 ])] 
print("Elements: ",newnp)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
  
# Index values can be negative. 
arr = a[np.array([1, 3, -3])]
print("Elements: ", arr)

# [2 4 7]

# numpy indexing and slicing

	There are three kinds of indexing available: 
		record access, basic slicing, advanced indexing.
		Which one occurs depends on object.

In [ ]:
a = np.arange(20) 
print(a) 
  
# a[start:stop:step] 
print(a[-8:17:1])  
  
# The : operator means all elements till the end. 
print(a[10:])

In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a[:, 0]) # single row with 0 index column value
# print(a[:, 1])
# print(a[:, 2])

# print(a[0, :])
# print(a[1, :])

print(a[0:2, 1:3]) # a[row, column]
print(a[0:2, 0:2])

In [ ]:
np.random.seed(10)
vv = np.random.random((5, 4))
print(vv)

# print(vv[2:5, 1:2])
# print(vv[2:5, 1])
print(vv[2:-1, :])

# Advanced indexing


	Purely integer indexing:
		When integers are used for indexing.
		Each element of first dimension is paired with the element of the second dimension


In [ ]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

#Boolean Indexing

	
		This indexing has some boolean expression as the index. 
		Those elements are returned which satisfy that Boolean expression.
		It is used for filtering the desired element values.






In [ ]:
import numpy as np

a = np.array([10, 40, 80, 50, 100]) 
# print(a[a>50])


b = np.array([[5, 5],[4, 5],[16, 4]]) 
sumrow = b.sum(-1)
# print(sumrow)
print(b[sumrow%10==0])



```
a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1
a[:]         # a copy of the whole array
# There is also the step value, which can be used with any of the above:
```



```
a[start:end:step] # start through not past end, by step


a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items
Similarly, step may be a negative number:

a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed
```



#File read from local computer

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['train.txt'] ), sep=" " ,  header = None, dtype = 'Int64')
print(df)

#File read from google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
main_directory = '/content/drive/My Drive/Soft Computing/Assignment 1 HMM/train.txt'

In [ ]:
df1 = pd.read_csv(main_directory, sep=" " , header = None, dtype = 'Int64')
print(df1)